# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Safing
encoding: "utf-8"
lang: "en"
email: hello@safing.io
emailobfuscated: "=b!isfg>#nbjmup;ifmmpAtbgjoh/jp#?ifmmpAtbgjoh/jp=0b?"
description: > # this means to ignore newlines until "base_url:"
  Safing is a software that protects your privacy online. It's so easy, anyone can use it.
base_url: "/" # the subpath of your site, e.g. /blog
assets_url: "/assets/"
vendor_url: "/vendor/"
url: "https://safing.io" # the base hostname & protocol for your site
cover: "img/cover.jpg"
logo: "img/logo_name_70h_reduced.png"
twitter_username: SafingIO
github_username: Safing
markdown: kramdown
highlightjs_theme: "monokai_sublime"

excerpt_separator: "<!--break-->"
inter_post_navigation: false

our_values_url: "/our-values/"
jobs_url: "/jobs/"
podcast_url: "/podcast/"
technology_url: "/technology/"
community_hub_url: "/community-hub/"
contact_url: "/contact/"
terms_url: "/terms/"
privacy_url: "/privacy/"
whitepaper_url: "/files/whitepaper/"
cyberfreedom_url: https://twitter.com/davegson/status/1110216714871029761

collections:
  podcasts:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      type: "post"
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "podcast"
      permalink: /podcast/:year/:month/:day/:title/
      type: "podcast"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@SafingIO"                 # (User) Name to display in the footer link
#     url: https://twitter.com/SafingIO     # URL of your profile (leave blank to not display in footer)
#     desc: Follow us Twitter               # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts (social_sharing must be true for this)

github_url: https://github.com/Safing

social_sharing: false
communities:
  - reddit:
    name: Reddit
    icon: reddit
    username: r/safing
    url: https://reddit.com/r/safing
    desc: Join our Reddit
    share: false
  - github:
    name: GitHub
    icon: github
    username: Safing
    url: https://github.com/Safing
    desc: Fork us on GitHub
    share: false
  - twitter:
    name: Twitter
    icon: twitter
    username: SafingIO
    url: https://twitter.com/SafingIO
    desc: Follow me on Twitter
    share: false

donations:
  bitcoin:
    url: https://www.blockchain.com/btc/address/1AosdDyzd8PVUFTUEXoaJHTyPVHuKQxdmq?filter=2
  paypal:
    url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2QHNM78H9YC9L&source=url

### Podcast

podcast_feed_url: /podcast.xml
podcast_album_art: /assets/podcast/img/cover.png
podcast_owner: 'Safing'
podcast_email: 'hello@safing.io'
podcast_category: Business
podcast_subcategory_one: Entrepreneurship
podcast_explicit: "no"
podcast_author: safing.io
podcast_title: The Safing Podcast
podcast_subtitle: "The venture of a privacy company working hard to forge #cyberfreedom"
podcast_description: "Join the founders on their mission to help online citizens reclaim their privacy and enjoy #cyberfreedom. Have a look behind the scenes, understand their decision processes and help shaping the future by contributing to the community!"
podcast_summary: "Join the founders on their mission to help online citizens reclaim their privacy and enjoy #cyberfreedom. Have a look behind the scenes, understand their decision processes and help shaping the future by contributing to the community!"
